name: 'slack notificator'
description: 'Send slack notification'
Icon: 'bell'
Color: 'yellow'

inputs:
  webhookUrl:
    description: 'Slack webhook URL'
    required: true
  pullRequestData:
    description: 'Data of pull request which will be attach to message context in shape of {title: string, url: string, user: {url, login, avatarUrl}}}'
  messageContent:
    description: 'Custom message content'

runs:
  using: 'node12'
  main: 'dist/index.js'
